[project]
name = "wheelwitch"
revision = "1.0"
require_reason = false

[profiles.default]
KEYSTORE_PATH = { description = "Path to the release keystore, relative to the project root", required = false }
KEYSTORE_PASSWORD = { description = "Release keystore password", required = false }
KEY_ALIAS = { description = "Signing key alias", required = false }
KEY_PASSWORD = { description = "Signing key password", required = false }
