package com.skiletro.wheelwitch.data

/**
 * Pure INI string manipulation used by [DolphinTree.ensureRmcGameInis]
 * to force-disable cheats and RetroAchievements in Dolphin's `GameSettings/`
 * and `Config/RetroAchievements.ini` files.
 *
 * All functions are side-effect free and operate on INI text, mirroring
 * the [DolphinConfig] pattern so they can be unit tested without any
 * Android dependencies.
 */
object DolphinGameIni {

  /** Game-ID prefix used for the shared Mario Kart Wii GameINI. */
  const val RMC_PREFIX = "RMC"

  /** Notice added to the auto-generated RMC GameINI file. */
  const val GAME_INI_NOTICE =
    "# Auto-generated by Wheel Witch. Do NOT touch any of the values below, they might get deleted."

  /** Key of the "Dolphin.Core" section of INI files which determines whether cheats are enabled. */
  const val CHEATS_KEY = "EnableCheats"

  /**
   * Key of the "Achievements.Achievements" section of INI files
   * which determines whether RetroAchievements are enabled.
   */
  const val ACHIEVEMENTS_KEY = "Enabled"

  /** The boolean string we use to force-disable settings in Dolphin's INIs. */
  const val FORCE_DISABLE_VALUE = "False"

  /**
   * Ensures [key] = [value] exists under [section] in the INI
   * [content] by inserting a line for it in a correct position.
   */
  fun addIniKeyValue(
    content: String,
    section: String,
    key: String,
    value: String,
  ): String {
    val lines = content.lines()
    val outLines = mutableListOf<String>()
    val kvLine = "$key = $value"
    var added = false

    for (line in lines) {
      outLines.add(line)
      extractIniSection(line)?.takeIf { !added && it == section }?.let {
        outLines.add(kvLine)
        added = true
      }
    }

    if (!added) {
      if (lines.isNotEmpty() && lines.last().isNotBlank()) outLines.add("")
      outLines.add(section)
      outLines.add(kvLine)
      outLines.add("")
    }

    return outLines.joinToString("\n")
  }

  /**
   * Ensures [key] = [value] exists under [section] in the INI
   * [content] by appending lines at the end for it.
   */
  fun addIniKeyValueAtTheEnd(
    content: String,
    section: String,
    key: String,
    value: String,
  ): String {
    val lines = content.lines().toMutableList()
    val kvLine = "$key = $value"

    if (lines.isNotEmpty() && lines.last().isNotBlank()) lines.add("")
    lines.add(section)
    lines.add(kvLine)
    lines.add("")
    return lines.joinToString("\n")
  }

  /**
   * Checks whether the [line] of an INI file assigns to a key matching the [keyPredicate].
   */
  fun hasIniKeyMatching(line: String, keyPredicate: (String) -> Boolean): Boolean {
    if (line.isEmpty() || line.first() == '#') {
      return false
    }

    val end = line.indexOf('=')
    if (end < 0) {
      return false
    }

    val keyOfLine = line.substring(0, end).trim()
    return keyPredicate(keyOfLine)
  }

  /**
   * Checks whether the [line] of an INI file assigns to [key] in a case-insensitive manner.
   */
  fun hasIniKey(line: String, key: String): Boolean {
    return hasIniKeyMatching(line) { keyOfLine -> keyOfLine.equals(key, ignoreCase = true) }
  }

  /**
   * Removes all lines from [content] beginning with the known Wheel Witch GameINI notice, and
   * returns the resulting string.
   */
  fun removeAllBelowNotice(content: String): String {
    val lines = content.lines()
    val noticeIdx = lines.indexOf(GAME_INI_NOTICE)
    return (if (noticeIdx < 0) lines else lines.subList(0, noticeIdx)).joinToString("\n")
  }

  /**
   * Returns the section name including the brackets if [line] declares an INI section,
   * or null otherwise.
   */
  fun extractIniSection(line: String): String? {
    val sectionEnd = line.indexOf(']')
    if (sectionEnd < 0 || line[0] != '[') {
      return null
    }

    return line.substring(0, sectionEnd + 1)
  }

  /**
   * Renames all occurrences of a section [oldSection] (case-insensitive match) to [newSection]
   * and returns the result.
   */
  fun renameSection(
    content: String,
    oldSection: String,
    newSection: String,
  ): String {
    val lines = content.lines()
    val outLines = mutableListOf<String>()

    for (line in lines) {
      extractIniSection(line)?.let { currentSection ->
        if (currentSection.equals(oldSection, ignoreCase = true)) {
          outLines.add(line.replaceFirst(oldSection, newSection, ignoreCase = true))
          continue
        }
      }
      outLines.add(line)
    }

    return outLines.joinToString("\n")
  }

  /**
   * Removes every line matching [key] (case-insensitive key name)
   * within [section] in the INI [content]. Returns the
   * modified content, or the original if nothing changed.
   */
  fun removeIniKeyInSection(
    content: String,
    section: String,
    key: String,
  ): String {
    val lines = content.lines()
    val outLines = mutableListOf<String>()

    var currentSection: String? = null
    for (line in lines) {
      extractIniSection(line)?.let { section ->
        currentSection = section
      } ?: run {
        if (section.equals(currentSection, ignoreCase = true) && hasIniKey(line, key)) {
          continue
        }
      }
      outLines.add(line)
    }

    return outLines.joinToString("\n")
  }
}